// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetLatestFrames():Promise<Array<main.frameSnapshot>>;

export function Greet(arg1:string):Promise<string>;
